#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug  8 19:27:29 2019

@author: maulik
"""
count=0
for i in range(11):
    count=count+i
    print("First", i, 'numbers when added gives',count)
    print(count)