#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 15 12:55:58 2019

@author: maulik
"""
n,m = input().split()
n= int(n)
m=int(m)
matrix= []
for i in range(n):
    matrix.append([int(j) for j in input().split()])
    
def isBinary(matrix,n):
    for i in range(n):
        for j in range(m):
            if matrix[i][j]>1 or matrix[i][j]<0:
                return False
    return True
            
if isBinary(matrix,n)==True:
    print("YES", end="")
else:
    print("NO", end="")
