#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 30 19:43:45 2019

@author: maulik
"""

N,V1,V2= [int(i) for i in input().split()]
#Time taken by Arun
T1= ((2**(1/2))*N)/V1
#Time taken by cab
T2= 2*N/V2
if T1>T2:
    print("Cab")
else:
    print("Walk")