#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  8 15:55:42 2019

@author: maulik
"""

N=input()
A= [int(N) for N in input().split()]
dict1={}
count=0
k=int(input())
for i in A:
    temp= {count:i}
    count+=1
    dict1.update(temp)
m= dict1[k-1]
dict2={}
count1= 0
for value in sorted(dict1.values()):
    temp1= {count1:value}
    dict2.update(temp1)
    count1+=1


for key,value in dict2.items():
    
    if value==m:
        print(key+1)
    
    