#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  3 19:09:09 2019

@author: maulik
"""

import re
S= input("")
L= re.split("@",S)
name= re.split(".com",L[1])
print(name[0],end="")
