#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep  6 19:34:37 2019

@author: maulik
"""

N=input()
A= [int(N) for N in input().split()]
dict1={}
count=0
k=input()
for i in A:
    temp= {i:count}
    dict1.update(temp)
    count=count+1
print(dict1)
dict2={}
for key in sorted(dict1.keys()):
    temp2= {key:dict1[key]}
    dict2.update(temp2)
print(dict2)
print(dict2[k])


#[ for (key, value) in sorted(numbers.items())]