#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  8 18:53:58 2019

@author: maulik
"""

n= int(input())
dict1={}
for i in range(1,n+1):
    temp= {i:i**3}
    dict1.update(temp)
print(dict1)