#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 16 17:54:15 2019

@author: maulik
"""
#import turtle
#polygon = turtle.Turtle()
#num_sides = 6
#side_length = 70
#angle = 360.0 / num_sides
#for i in range(num_sides):
#    polygon.forward(side_length)
#    polygon.right(angle)
#turtle.done()

import turtle
t=turtle.Pen()
for i in range(4):
	t.forward(60)
	t.left(90)	