#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 21 19:34:18 2019

@author: maulik
"""


L1= [int(N) for N in input().split()]
M=len(L1)
L2=[]
for i in range(M):
    temp= L1[i]
    if temp not in L2[:]:
        L2.append(temp)
print(L2,end="")