#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 30 16:16:31 2019

@author: maulik
"""

n= input()
n= int(n)

if n%2!=0:
    print("Weird")
elif n%2==0 and n in range(2,6):
    print("Not Weird")
elif n%2==0 and n in range(6,20):
    print("Weird")
elif n%2==0 and n>20:
    print("Not Weird")
    
    