#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 13 18:00:54 2019

@author: maulik
"""
N=input("Enter the last number ")
N=int(N)
for i in range(N):
    if i%3==0 and i%5==0:
        print(i,"fizzbuzz")
    else:    
        if i%3 == 0:
            print(i,"fizz")
        else:
            if i%5==0:
                print(i,'buzz')