#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 17 19:06:38 2019

@author: maulik
"""

import numpy as np
import random
from scipy.fftpack import dct
I= np.random.randint(0,256,size=(8,8))
Idct= dct(dct(I).T).T
Iarray= np.array(Idct)
Iarray= round(Irray,)

