#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 10 17:43:38 2019

@author: maulik
"""

N= int(input())
if (N%3==0) or  ((N%2!=0) and ((N-1)%3==0)):
    print("YES",end="")
else:
    print("NO", end="")