#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 30 19:45:59 2019

@author: maulik
"""

def isleapyear(year):
    if year%4==0:
        if year%100==0 and year%400!=0:
            return False
        else:
            return True

year =int(input())
if isleapyear(year)==True:
    print("It is a leap year" )
else:
    print("not a leap year")
    