#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 12 17:14:50 2019

@author: maulik
"""
n= int(input())
matrix= []
for i in range(n):
    matrix.append([int(x) for x in input().split()])
    

for i in range(0,n-1):
    for j in range(i+1, n):
        matrix[i][j]= 0

for i in range(0,n):
    for j in range(0,n):
        if j==n-1:
            print(matrix[i][j],end= "")
        else:
            print(matrix[i][j],end= " ")
    if i<n-1:
    	print()