#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 16 22:40:15 2019

@author: maulik
"""

a,b=input().split()
a=int(a)
b=int(b)
matrix=[]
c=1
c=int(c)
for i in range(0,a):
    x=[]
    for j in range(0,b):
        x.append(c)
        c=c+1
    matrix.append(x)
 
for i in range(0,a):
    for j in range(0,b):
        if j<b-1:
            print(matrix[i][j],end=" ")
        else:
            print(matrix[i][j], end="")
    if i<a-1:
        print()

       