#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 21 20:01:15 2019

@author: maulik
"""
import string
S1=input("")
S2= string.ascii_lowercase
S1= S1.lower()

def panagram(S1,S2):
    for char in S2:
        if char not in S1:
            return False
            
    else:
        return True
    
if (panagram(S1,S2)==True):
    print("YES", end="")
else:
    print("NO", end="")


