#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 22 12:10:45 2019

@author: maulik
"""

import string
S1=input("")
S2= string.ascii_letters
L1= list(S1)
L2= list(S2)

    
def panagram(S1,S2):
    for m in range(26):
       
        if (S2[m] or S2[m+26]) not in S1:
            
            return False
           
    else:
        return True
    
if (panagram(S1,S2)==True):
    print("YES", end="") 
else:
    print("NO", end="")
    