#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 30 19:55:16 2019

@author: maulik
"""

N= int(input())
L=[]
for i in range(1,N+1):
    i=str(i)
    L.append(i)
S= "".join(L)
print(S)
    