#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  8 19:02:02 2019

@author: maulik
"""

def printDict():
    n= int(input())
    dict1={}
    for i in range (1, n+1):
        temp = {i:i**2}
        dict1.update(temp)
    print(dict1,end="")
    return

printDict()