#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 30 23:16:23 2019

@author: maulik
"""

A= [int(N) for N in input().split()]
B= sorted(A)
while True:
    if A==B:
        break
    else:
        for 