#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  4 16:29:13 2019

@author: maulik
"""

A= [int(N) for N in input().split()]
n=len(A)
C= sorted(A)

count=0
for i in range(n):
    B= A[i:]
    min1= min(B)
    if A[i]== min1:
        count=count
    else:
        count=count+1
print(count)