#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 31 20:05:35 2019

@author: maulik
"""

A= [int(N) for N in input().split()]
n=len(A)
C= sorted(A)
count=0
D=A      
for i in range(len(A)):
    print(i)
    B= A[i:]
    print(B)
    min1= min(B)
    if A[i]!=min1:
        temp= A[i]
        A[i]=min1
        print(A[i])
        print(A)
        for k in range(i+1,n-1):
                print(k)
                A[k]= A[k+1]
                print(A[k])
        A[-1]= temp
           
print(A)
  
    