#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  1 17:03:11 2019

@author: maulik
"""

A = [int(N) for N in input().split()]
B = sorted(A)
n= len(A)
temp1=n
temp2=0
for i in range(n):
    if A[i] == B[temp2]:
        temp1= temp1-1
        temp2=temp2+1
print(temp1)
