#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 27 19:28:56 2019

@author: maulik
"""


n= int(input())
matrix= []
for i in range(n):
    matrix.append([int(x) for x in input().split()])
print(matrix)
A=[]
for j in range(n):
    if j%2==0:
        i=0
        while i<n:
            temp=matrix[i][j]
            A.append(temp)
            
            i=i+1
    elif j%2 !=0:
        i= n-1
        while i>=0:
            temp=matrix[i][j]
            A.append(temp)
            i=i-1
            
print(*A, end='')
.         