#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  1 19:16:49 2019

@author: maulik
"""
n= int(input())
matrix= []
for i in range(n):
    matrix.append([int(x) for x in input().split()])

A=[]
k=0
m=0

for i in range(k,n):
    A.append(matrix[i][m])
    
m=m+1
k=i

for j in range(m,n):
    A.append(matrix[k][j])
m=j   
for i in range(k-1,-1,-1):
    A.append(matrix[i][m])

k=i


for j in range(m-1, 0, -1) :
    A.append((matrix[i][j]))
m=j

k=i+1
A.append(matrix([k][m]))
    
    
        