#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 14 19:32:33 2019

@author: maulik
"""

n= int(input())
matrix= []
for i in range(n):
    matrix.append([int(x) for x in input().split()])
    
def ifSymmetric(matrix,n):
    for i in range(n-1):
        for j in range(i+1,n):
            if matrix[i][j]==matrix[j][i]:
                return True
            else:
                return False

if ifSymmetric(matrix,n):
    print("Yes")
else:
    print("NO")