#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 22 18:47:34 2019

@author: maulik
"""

S1= input("")
S2="aeiou"
L1= S1.split()
L2= S2.split()

def vowels(S1,S2):
    for i in range(len(S1)-1):
        if (S1[i] and S1[i+1]) in S2:
            print(S1[i], S1[i+1])
            return True
    else:
        return False
    
if (vowels(S1,S2)==True):
    print("yes")
else:
    print("No")